/* Generated by Yosys 0.44 (git sha1 80ba43d26, clang++ 15.0.0 -fPIC -O3) */

(* hdlname = "jfulladder" *)
(* top =  1  *)
(* src = "test2.v:1.1-8.10" *)
module jfulladder(y, carryout, a, b, carryin);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "test2.v:3.9-3.10" *)
  input a;
  wire a;
  (* src = "test2.v:3.11-3.12" *)
  input b;
  wire b;
  (* src = "test2.v:3.13-3.20" *)
  input carryin;
  wire carryin;
  (* src = "test2.v:2.12-2.20" *)
  output carryout;
  wire carryout;
  (* src = "test2.v:2.10-2.11" *)
  output y;
  wire y;
  OR _06_ (
    .A(b),
    .B(carryin),
    .Y(_02_)
  );
  NAND _07_ (
    .A(b),
    .B(carryin),
    .Y(_03_)
  );
  NAND _08_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  NAND _09_ (
    .A(a),
    .B(_04_),
    .Y(_05_)
  );
  OR _10_ (
    .A(a),
    .B(_04_),
    .Y(_00_)
  );
  NAND _11_ (
    .A(_05_),
    .B(_00_),
    .Y(y)
  );
  NAND _12_ (
    .A(a),
    .B(_02_),
    .Y(_01_)
  );
  NAND _13_ (
    .A(_03_),
    .B(_01_),
    .Y(carryout)
  );
endmodule
