/* Generated by Yosys 0.44 (git sha1 80ba43d26, clang++ 15.0.0 -fPIC -O3) */

(* hdlname = "SimpleDFF" *)
(* top =  1  *)
(* src = "dff.v:2.1-13.10" *)
module SimpleDFF(D, C, Q);
  (* src = "dff.v:4.16-4.17" *)
  input C;
  wire C;
  (* src = "dff.v:3.16-3.17" *)
  input D;
  wire D;
  (* src = "dff.v:5.16-5.17" *)
  output Q;
  wire Q;
  (* src = "dff.v:9.5-11.8" *)
  DFF _0_ (
    .C(C),
    .D(D),
    .Q(Q)
  );
endmodule
